global:
  domain: argocd.local

certificate:
  enabled: true

redis-ha:
  enabled: false

controller:
  replicas: 1

server:
  replicas: 1
  ingress:
    enabled: true
    ingressClassName: nginx
    tls: true
    annotations:
      nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"

repoServer:
  replicas: 1

applicationSet:
  replicas: 1
